first_name: John
last_name: Doe
dob: 01/01/2000 # mm/dd/yyyy
last_4_ssn: 9999
email: john.doe@gmail.com


date: 12/31/2024 # mm/dd/yyyy
time:
  start: "15:00" # 24 hour format
  end: "17:00" # 24 hour format

type_id: 81 # 71 for first time, 81 for renewal

zip_code: 12345
miles_within: 10

manual_mode: true # Set to true for manual login, false for automated
